#!/bin/sh /etc/rc.common

START=99  # Set the priority of startup, 99 is the lowest and 1 is the highest.

start() {        
    echo starting trb141_mqtt_io_uptime...

    # Launch application
    python3 /trb141_mqtt_io_uptime/main.py &
}
stop() {
    echo stoping trb141_mqtt_io_uptime...
    # Kill application
    killall python3
}
